# Makefile
# -------------------------------------------------------------------------------------------------
# course:   System Programming
# project:  (#3) Travel Monitor (sockets, threads)
# name:     George Tservenis
# email:    sdi1500164@di.uoa.gr
# -------------------------------------------------------------------------------------------------

#LS1 = ./src/travelmonitor.c ./src/monitor.c ./src/handler.c
#LS2 = ./src/travelmonitor.c ./src/monitor.c
#
#SRC1:=$(filter-out $(LS1), $(wildcard ./src/*.c))
#SRC2:=$(filter-out $(LS2), $(wildcard ./src/*.c))
#
#EXE = travelMonitor
#CC  = gcc
#CFL = -O2 -g
#LIB = -lm
#
#all: compile_monitor compile_travelmonitor
#
#compile_monitor:
#	$(CC) $(CFL) ./src/monitor.c $(SRC1) -o ./monitor $(LIB)
#
#compile_travelmonitor:
#	$(CC) $(CFL) ./src/travelmonitor.c $(SRC2) -o $(EXE) $(LIB)
#
#clean:
#	rm -f ./travelMonitor ./monitor
